### ISSUE TITLE
License

### ISSUE THREAD

**Issue by prataffel** [papis/papis-vim#9]
Hey @alejandrogallo, hey all,

Thanks, again, for all your effort developing papis. 

I am aware that this little plugin is not maintained actively at the moment; nevertheless, I think it would be great if you could define a license for the code. I don't want to be picky with this -- it's just more convenient for people that modify this script.

**Comment by alejandrogallo** [comment]
Hi, 

sure I just added a license now.
Is this the format that is acceptable?
I always forget exactly what format is necessary.

thanks for noticing!

**Comment by prataffel** [comment]
Thanks!
